### PR TITLE
Various changes to the Python Tutorial

### PR DESCRIPTION
**Pull request by chrisnorman7**
Made some stylistic changes to the Python tutorial, and added extra commands to the audio player.

Describe the feature and/or bug fix:

There were a couple of small bugs in the audio player example, which I hopefully fixed. I also added a couple of extra commands to it (namely loop and gain), to show off more of Synthizer's capabilities.

To stop VSCode moaning while I was linting, I also put in language qualifiers in markdown code blocks.

Finally, I do declare:
I have read CONTRIBUTING.md, am the sole contributor to this pull request, and license my contributions under the Unlicense.

### CODE REVIEW

**Comment by camlorn** [comment]
I'll review this in detail this weekend, but can you backport your changes to bindings/python/example.py? I'm keeping that in sync with the manual.

**Comment by chrisnorman7** [comment]
OK, that's no problem.

I've clicked the pull request link again, and apparently it's waiting for
AppVeyor to complete.

Not sure if I did the right thing or not haha, I've never updated a pull
request like this before.

Another slight thing: In the manual, you say how buffers are completely
decoupled from contexts, yet the first argument to Buffer has to be a
context. Does that need explaining in the manual?

Take care,

Chris Norman

**Comment by camlorn** [comment]
Just git pushing the commit to the branch that the pull request is based off is sufficient as long as there's a PR open for that branch in the web UI already.  GitHub will pick it up automatically and restart CI automatically.  CI is automated building in the cloud and doesn't matter here because this is just documentation changes, but that needs to pass for merge and takes around 15 minutes per run (but don't worry, it's free for open source projects).

The buffer thing is one of those cases where the documentation is ahead of reality, and the library will be brought in line. I need to check the implementation and figure out why it actually takes a context, then remove the dependency.  I think I just originally decided that I didn't want to commit to separating them, then never actually separated them when I did.

**Comment by chrisnorman7** [comment]
OK great stuff. Well all my pushes should be done now, so feel free to
review at your leisure.

Take care,

Chris Norman

**Pull request merged**
