### PR TITLE
Fixed a typo.

### PR DESCRIPTION
**Pull request by chrisnorman7**
Describe the feature and/or bug fix:

Removed the extra s in "transaction-like".

This is for issue: N/A

### CODE REVIEW

**Comment by ahicks92** [comment]
Thanks, but can you get rid of all the changes in this diff that aren't just that one line?  You're dropping in a bunch of stuff that maybe you didn't mean to here.  Looks like a bunch of indentation changes and some .vscode stuff.

**Comment by chrisnorman7** [comment]
OK, sorry about that. I didn't realise I was autoformatting everything.

Hopefully that's fixed now.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
It looks like it's not, but this is a one line change so I'll just do it manually.

**Comment by chrisnorman7** [comment]
Oh sorry. Apparently I've no idea what I'm doing.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
Fixed on the 0.9-dev branch

**Pull request closed without merging**
